name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Build & Test Backend
  build-backend:
    name: Build & Test Spring Boot Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build with Maven
        run: mvn clean verify

      - name: Build Backend Docker Image
        run: docker build -t cpb-demo-backend .

  # Build Frontend
  build-frontend:
    name: Build NGINX Frontend Docker Image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Frontend Docker Image
        run: docker build -t cpb-demo-frontend .

  # Integration Test mit Docker Compose
  compose-test:
    name: Docker Compose Integration Test
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose and Start all Services
        run: |
          docker-compose up -d --build
          sleep 30 # Warte auf Container-Startup
          docker-compose ps

      - name: Test Backend Health Endpoint
        run: |
          curl --fail http://localhost:8080/actuator/health || exit 1

      - name: Shutdown Docker Compose
        run: docker-compose down